### ISSUE TITLE
自动排班需求

### ISSUE THREAD

**Issue by GroovingChloeee** [Liyuk/duty-roster#1]
**INPUT:**
[name_id: num_of_shifts]*10  _##每个同学的id，及上班shift数_
[shift_id: num_of_name_needed]*90 ##每个shift的id，及需要上班的人数

**OUTPUT:**
[shift_id: name_id]  _##每个shift_id对应的name_id，以dictionary形式展示_

**RULES：**
1. shift属性分为3种: e_shift, l_shift, nor_shift shift_id，对应类型default的需要上班人数分别为num_of_name_needed_e_shift = num_of_name_needed_l_shift=1, num_of_name_needed_nor_shift = 7, 且实际num_of_name_needed可根据shift_id进行编辑。
2. 每个name_id对应的(num_of_e_shift + num_of_l_shift)/(num_of_shift)数值尽量相等

**Comment by Liyuk** [comment]
需求评估 fail
